### ISSUE TITLE
Stworzyć listę funkcjonalności w apce

### ISSUE THREAD

**Issue by kamilsobik** [kamilsobik/financial-app#7]
- Dodawanie wydatków i przypisanie ich do odpowiedniej kategorii,
- Historia wydatków podzielona na kategorie z możliwością filtrowania po kategoriach i okresach,
- Wykres przedstawiający sumę wydatków z każdej kategorii w danym miesiącu

**Comment by RobertDebicki** [comment]
- Limit wydatków na daną kategorię
- Powiadomienie o zbliżającym się limicie

**Comment by kamilsobik** [comment]
Done!
